### ISSUE TITLE
flutter環境構築(Mac)

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/The4thDay-of-MikkaBozu#2]
メンバー：@kugimasa, @TakedaHiroki, @TakedaHiroki 
## インストール
- [x] : [XCode (Ver 11.4.1)](https://apps.apple.com/jp/app/xcode/id497799835?mt=12)
- [x] : [Android Studio (Ver 3.6.3)](https://developer.android.com/studio/install)
- [x] : [Flutter SDK](https://flutter.dev/docs/get-started/install/macos)

## TODO
- [x] **Step 1 : OSのバージョン確認**
- macOS Catalina -> .zshrc
- それ以外 -> .bashrc

(余談) macOS Catalinaからライセンシング関係で**zsh**推奨になったとのこと。[詳しくはコチラ](https://thenextweb.com/dd/2019/06/04/why-does-macos-catalina-use-zsh-instead-of-bash-licensing/)

- [x] **Step2 : パスを更新**
```zsh
export PATH="$PATH:$HOME/flutter/bin"
```
**unzip**した`flutter`ディレクトリまでのパスを指定

- [x] **Step3 : flutter SDKの確認**
バージョンの確認
```zsh
flutter --version
```
必要なものの確認
```zsh
flutter doctor
```

- [x] **Step4 : Android Studio に Flutter Plugin をインストール**

- [x] **Step5 : Android Studio の設定 (お好みで)**
- KeyMapping
- Hot Reload
- Font Size

- [x] **Step6 : Flutter Projectを作成**
- [x] **Step7 : エミュレーターを動かす**
  - [x] iOS
  - [x] Android : Nexus 6 (Pi)
